params:
  max_epochs: 10

model:
  model_name: "resnet18"
  num_classes: 100
  pretrained: true
  lr: 1e-2
  weight_decay: 0
  momentum: 0.9
  nesterov: true

data:
  dataset_path: ???
  train_batch_size: 32
  inference_batch_size: 256
  num_workers: 8