hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

trainer:
  gpus: ???
  max_epochs: 10
  val_check_interval: 0.2

model:
  model_name: "resnet18"
  num_classes: 100
  pretrained: true
  lr: 1e-2
  weight_decay: 0
  momentum: 0.9
  nesterov: true

data:
  dataset_path: ???
  minigeolifeclef: True
  train_batch_size: 32
  inference_batch_size: 256
  num_workers: 8